#! /usr/bin/bash

LATEST_BLOB=$(curl -s https://api.github.com/repos/shawnrushefsky/collie/releases/latest)
ASSETS=$(echo $LATEST_BLOB | jq -r ".assets[] | @base64")

for asset in $ASSETS; do
  FILENAME=$(echo $asset | base64 --decode | jq -r ".name")
  DOWNLOAD_URL=$(echo $asset | base64 --decode | jq -r ".browser_download_url")
  curl -L $DOWNLOAD_URL --output $FILENAME
done